# Generated by Django 4.2 on 2023-05-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonApp', '0004_remove_route_name_remove_route_route_detail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='googleMap',
            field=models.CharField(default='', max_length=300),
        ),
    ]
