# Generated by Django 4.2 on 2023-05-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonApp', '0005_store_googlemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(default='', max_length=500),
        ),
    ]
