# Generated by Django 4.2 on 2023-05-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragonApp', '0006_store_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='store_id',
        ),
    ]
