# Generated by Django 4.2 on 2023-05-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragonApp', '0007_remove_user_date_joined_remove_user_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
