# Generated by Django 4.2 on 2023-05-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragonApp', '0011_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='quantity',
        ),
    ]
