# Generated by Django 4.2 on 2023-05-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragonApp', '0012_remove_vehicle_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='num_stores',
        ),
    ]
